### PR TITLE
Create auth.js

### PR DESCRIPTION
**Pull request by redixhumayun**
Basic authorization example to explain how the OAuth 2 flow occurs. Uses basic classes to simulate interfacing between Client, App and Server.
Use this as a workshop to show how ES6 classes work while simultaneously showing how authorization on the web occurs. 
Just a basic skeleton right now.

### CODE REVIEW

**Comment by maneesht** [comment]
What is this for?

**Comment by redixhumayun** [comment]
Its for workshop 3. I floated an idea past Anubhav, and we decided to write a PR and flesh it out.

**Comment by redixhumayun** [comment]
Okay, I've added a new client-server.js file. I've tried to provide a balance between making it simple and actually showing some functionality of a client and server.
Also tried to include some stuff they've covered in the lessons so far.

**Comment by maneesht** [comment]
This not bad. I like this idea. However, are we thinking of this being a workshop? If so, this may be outside of their capabilities

**Comment by redixhumayun** [comment]
Sorry, are you talking about the auth.js file or the client-server.js file? I should have deleted the auth.js file since that was the old idea, but I decided to leave it up there just in case.

**Comment by maneesht** [comment]
client-server.js

**Comment by redixhumayun** [comment]
Yeah, I was thinking about using it as a workshop. 
Maybe it would be best to just go with the calculator in that case...

**Comment by maneesht** [comment]
Don't give up so easily :-) maybe @marsha88 can give his opinion

**Comment by claytn** [comment]
Some may do well with this, but I have a feeling the majority of them would be much more comfortable solidifying their knowledge by building something more simple like a calculator. This could be like a bonus task for them to do if they finish the calculator quickly though

**Pull request closed without merging**
